import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

type LinkingCardProps = {
  name: string;
  description: string;
  slug: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Simple ToDo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Simple <span className="text-purple-300">ToDo</span> App
        </h1>

        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3">
          <LinkingCard
            name="TODOs"
            description="TODOs Example page"
            slug="/todos"
          />
        </div>
      </main>
    </>
  );
};

const LinkingCard = ({
  name,
  description,
  slug: documentation,
}: LinkingCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <Link
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
      >
        Try
      </Link>
    </section>
  );
};

export default Home;
